# action.yml
name: 'Archive'
description: 'Create a release zip for WordPress Plugins or Themes'
runs:
  using: 'docker'
  image: 'Dockerfile'
outputs:
  file:
    description: 'Output zip file of the plugin or theme'